Neos:
  ContentRepositoryRegistry:
    presets:
      'default':
        projections:
          'Neos.Workspace.Ui:TrashBinProjection':
            factoryObjectName: Neos\Workspace\Ui\Domain\TrashBin\TrashBinProjectionFactory
