exclude_paths:
  - 'Neos.Media/Resources/Public/Libraries/*'
  - 'Neos.Neos/Resources/Public/Library/*'
  - 'Neos.Neos/Tests/*'
  - 'Neos.Media/Tests/*'
  - 'Neos.Media.Browser/Tests/*'
  - 'Neos.SiteKickstarter/Tests/*'
  - 'Neos.NodeTypes/Tests/*'
  - 'Neos.ContentRepository/Tests/*'
  - 'Neos.Fusion/Tests/*'
  - 'Neos.Diff/Tests/*'
  - 'Neos.Neos/Migrations/*'
  - 'Neos.ContentRepository/Migrations/*'
  - 'Neos.Media/Migrations/*'
  - 'Neos.Media.Browser/Migrations/*'
  - 'Neos.Diff/Migrations/*'
