preset: psr2

finder:
  path:
    - "Neos.ContentRepository/Classes"
    - "Neos.ContentRepository/Tests"
    - "Neos.Diff/Classes"
    - "Neos.Diff/Tests"
    - "Neos.Fusion/Classes"
    - "Neos.Fusion/Tests"
    - "Neos.Media.Browser/Classes"
    - "Neos.Media.Browser/Tests"
    - "Neos.Media/Classes"
    - "Neos.Media/Tests"
    - "Neos.Neos/Classes"
    - "Neos.Neos/Tests"
    - "Neos.NodeTypes/Classes"
    - "Neos.NodeTypes/Tests"
    - "Neos.SiteKickstarter/Classes"
    - "Neos.SiteKickstarter/Tests"
