preset: psr2

finder:
  path:
    - "TYPO3.Media/Classes"
    - "TYPO3.Media/Tests"
    - "TYPO3.Neos/Classes"
    - "TYPO3.Neos/Tests"
    - "TYPO3.Neos.Kickstarter/Classes"
    - "TYPO3.Neos.Kickstarter/Tests"
    - "TYPO3.Neos.NodeTypes/Classes"
    - "TYPO3.Neos.NodeTypes/Tests"
    - "TYPO3.TYPO3CR/Classes"
    - "TYPO3.TYPO3CR/Tests"
    - "TYPO3.TypoScript/Classes"
    - "TYPO3.TypoScript/Tests"
