Neos:
  ContentRepositoryRegistry:
    presets:
      'default':
        projections:
          # NOTE: the following name must be stable, because we use it f.e. in Neos UI to register
          # catchUpHooks for content cache flushing
          'Neos.ContentRepository:ContentGraph':
            factoryObjectName: Neos\ContentGraph\DoctrineDbalAdapter\DoctrineDbalContentGraphProjectionFactory
