# This file is mounted into the Docker container in "docker-compose-full.yml"
Neos:
  Flow:
    persistence:
      backendOptions:
        driver: 'pdo_mysql'
        charset: 'utf8mb4'
        host: 'mysql'
        port: 3306
        user: 'root'
        password: db

        dbname: 'neos_behat'

  ContentRepositoryRegistry:
    postgres:
      persistence:
        backendOptions:
          driver: pdo_pgsql
          # see docker-compose-full.yml
          host: 'postgres'
          port: 5432
          dbname: 'neos_behat'
          user: 'root'
          password: 'db'
          charset: 'UTF8'

    # We enable the race condition tracker. For details on how this works, see RaceTrackerContentRepositoryHook.php
    presets:
      'default':
        hooks:
          'Neos.ContentRepository.BehavioralTests:RaceConditionTracker':
            factoryObjectName: Neos\ContentRepository\BehavioralTests\ProjectionRaceConditionTester\RaceTrackerContentRepositoryHookFactory
  ContentRepository:
    BehavioralTests:
      raceConditionTracker:
        enabled: true
        redis:
          host: redis
          port: 6379
