<?php

/*
 * This file is part of the Neos.ContentRepository package.
 *
 * (c) Contributors of the Neos Project - www.neos.io
 *
 * This package is Open Source Software. For the full copyright and license
 * information, please view the LICENSE file which was distributed with this
 * source code.
 */

declare(strict_types=1);

namespace Neos\ContentRepository\Core\Projection\ContentGraph;

use Neos\ContentRepository\Core\SharedModel\Node\NodeAggregateId;
use Neos\ContentRepository\Core\SharedModel\Node\NodeName;
use Neos\ContentRepository\Core\DimensionSpace\OriginDimensionSpacePoint;
use Neos\ContentRepository\Core\SharedModel\Node\NodeAggregateClassification;
use Neos\ContentRepository\Core\NodeType\NodeType;
use Neos\ContentRepository\Core\NodeType\NodeTypeName;
use Neos\ContentRepositoryRegistry\ContentRepositoryRegistry;

/**
 * Main read model of the {@see ContentSubgraphInterface}.
 *
 * Immutable, Read Only. In case you want to modify it, you need
 * to create Commands and send them to ContentRepository::handle.
 *
 * The node does not have structure information, i.e. no infos
 * about its children. To f.e. fetch children, you need to fetch
 * the subgraph via $node->subgraphIdentity and then
 * call findChildNodes() on the subgraph.
 *
 *
 * @api
 */
final class Node
{
    public function __construct(
        public readonly ContentSubgraphIdentity $subgraphIdentity,
        /**
         * NodeAggregateId (identifier) of this node
         * This is part of the node's "Read Model" identity, whis is defined by:
         * - {@see getSubgraphIdentitity}
         * - {@see getNodeAggregateId} (this method)
         *
         * With the above information, you can fetch a Subgraph using {@see ContentGraphInterface::getSubgraph()}.
         * or {@see ContentRepositoryRegistry::subgraphForNode()}
         */
        public readonly NodeAggregateId $nodeAggregateId,
        /**
         * returns the DimensionSpacePoint the node is at home in. Usually needed to address a Node in a NodeAggregate
         * in order to update it.
         */
        public readonly OriginDimensionSpacePoint $originDimensionSpacePoint,
        public readonly NodeAggregateClassification $classification,
        public readonly NodeTypeName $nodeTypeName,
        public readonly NodeType $nodeType,
        /**
         * Returns all properties of this node. References are NOT part of this API;
         * there you need to check getReference() and getReferences().
         *
         * To read the serialized properties, call properties->serialized().
         *
         * @return PropertyCollectionInterface Property values, indexed by their name
         */
        public readonly PropertyCollectionInterface $properties,
        public readonly ?NodeName $nodeName,
        public readonly Timestamps $timestamps,
    ) {
    }

    /**
     * Returns the specified property.
     *
     * If the node has a content object attached, the property will be fetched
     * there if it is gettable.
     *
     * @param string $propertyName Name of the property
     * @return mixed value of the property
     * @api
     */
    public function getProperty(string $propertyName): mixed
    {
        return $this->properties[$propertyName];
    }

    /**
     * If this node has a property with the given name. Does NOT check the NodeType; but checks
     * for a non-NULL property value.
     *
     * @param string $propertyName
     * @return boolean
     * @api
     */
    public function hasProperty(string $propertyName): bool
    {
        return $this->properties->offsetExists($propertyName);
    }

    /**
     * Returns the node label as generated by the configured node label generator
     *
     * @return string
     */
    public function getLabel(): string
    {
        return $this->nodeType->getNodeLabelGenerator()->getLabel($this);
    }

    public function equals(Node $other): bool
    {
        return $this->subgraphIdentity->equals($other->subgraphIdentity)
            && $this->nodeAggregateId->equals($other->nodeAggregateId);
    }
}
