<?php
declare(strict_types=1);

namespace Neos\ContentRepository\Api\Domain;

/*
 * This file is part of the Neos.ContentRepository.Api package.
 *
 * (c) Contributors of the Neos Project - www.neos.io
 *
 * This package is Open Source Software. For the full copyright and license
 * information, please view the LICENSE file which was distributed with this
 * source code.
 */

use Neos\ContentRepository\Domain\Model\NodeType;
use Neos\ContentRepository\Domain\NodeAggregate\NodeName;
use Neos\ContentRepository\Domain\NodeType\NodeTypeName;

/**
 * The feature interface declaring access to node metadata
 */
interface NodeMetadataInterface
{
    /**
     * Whether or not this node is the root of the graph, i.e. has no parent node
     */
    public function isRoot(): bool;

    /**
     * Whether or not this node is tethered to its parent, fka auto created child node
     */
    public function isTethered(): bool;

    public function getNodeTypeName(): NodeTypeName;

    public function getNodeType(): NodeType;

    public function getNodeName(): ?NodeName;

    /**
     * Returns the node label as generated by the configured node label generator
     */
    public function getLabel(): string;
}
