Neos:
  ContentRepositoryRegistry:
    presets:
      'default':
        projections:
          'Neos.ContentRepository:ContentGraph':
            factoryObjectName: Neos\ContentGraph\PostgreSQLAdapter\HypergraphProjectionFactory

