##
# Thumbnail

-
  name:  'Thumbnail'
  uriPattern: 'media/thumbnail/{thumbnail}'
  defaults:
    '@package':    'TYPO3.Media'
    '@controller': 'Thumbnail'
    '@action':     'thumbnail'
  httpMethods: ['GET']
