Neos:
  Flow:
    persistence:
      doctrine:
        eventListeners:
          Neos\Media\Domain\EventListener\ImageEventListener:
            events:
              - postRemove
            listener: Neos\Media\Domain\EventListener\ImageEventListener
    mvc:
      routes:
        Neos.Media: true

  Media:
    # Enable asynchronous thumbnails
    asyncThumbnails: true
    # Thumbnail presets
    thumbnailPresets: { }
    # Automatically create thumbnails for configured presets when assets are added
    autoCreateThumbnailPresets: true

    iconSet:
      path: 'resource://Neos.Media/Public/IconSets/vivid'
      extension: 'svg'

    assetSources:
      'neos':
        assetSource: 'Neos\Media\Domain\Model\AssetSource\Neos\NeosAssetSource'
        assetSourceOptions:
          icon: 'resource://Neos.Media/Public/Icons/NeosWhite.svg'
          description: 'Assets in the local asset storage'
          # asyncThumbnails: defaults to the value of Neos:Media:asyncThumbnails
          asyncThumbnails: ~


    asset:
      modelMappingStrategy:
        default: Neos\Media\Domain\Model\Document
        patterns:
          '[image/x-icon]':
            className: Neos\Media\Domain\Model\Document
          '[image/.*]':
            className: Neos\Media\Domain\Model\Image
          '[audio/.*]':
            className: Neos\Media\Domain\Model\Audio
          '[video/.*]':
            className: Neos\Media\Domain\Model\Video

    image:
      defaultOptions:
        # Image quality, from 0 to 100
        quality: 90
        convertCMYKToRGB: true
        # Image formats that shall always be converted regardless wether an adjustment was applied or not
        # The key is the the source media-type and the value is the target media-type or file-extension
        # like "image/tiff: image/jpeg". Please ensure the target format is supported by the imagine-driver.
        convertFormats: [ ]
        interlace: '%\Imagine\Image\ImageInterface::INTERLACE_NONE%'
        # defines the filter to use for resize operations.
        # Note that the default GD driver only supports the FILTER_UNDEFINED.
        # Check the \Imagine\Image\ImageInterface class for a reference of all filters.
        # They roughly line up with ImageMagick filters, so read up on those to see differences.
        # A very cheap filter with reasonable quality would be "FILTER_BOX", alternative is "FILTER_CATROM".
        resizeFilter: '%\Imagine\Image\ImageInterface::FILTER_UNDEFINED%'

    imagor:
      # Imagor is a vips based image proxy which can be used for fast async image processing.
      enabled: true

      # If empty, all original asset resources will use the current request to get the base url.
      # When not empty will replace the calculated domain with this one.
      # Required when imagor is deployed in a container setup where imagor will directly call
      # neos for the original image.
      # Sample for Docker Development environment:
      #   sourceBaseUrl: 'http://neos:8081'
      #   proxyBaseUrl: 'http://127.0.0.1:8000'
      sourceBaseUrl: 'http://neos:8081'

      # This is the url of the imagor instance. Can be a full uri or a relative path:
      # Full url sample:
      #   proxyBaseUrl: 'http://127.0.0.1:8000'
      # Path sample:
      #   proxyBaseUrl: '/imagor'
      #   This will use the requests domain as base and append the path for imagor
      #   Like: https://my.neos.com/imagor
      #   In this case you must configure your webserver to redirect all /imagor traffic to
      #   your imagor service/container.
      proxyBaseUrl: 'http://127.0.0.1:8000'
      # only as path => use current port and host + this path
      # proxyBaseUrl: '/imagor'

      # by default, we use imagor in unsecure mode, add shared secret for request signing
      # see https://github.com/cshum/imagor?tab=readme-ov-file#security for details
      secret: ~
      signerType: sha256
      signerTruncate: 40

    # Variant presets
    variantPresets: [ ]
    # Automatically create asset variants for configured presets when assets are added
    autoCreateImageVariantPresets: true

    thumbnailGenerators:

      Neos\Media\Domain\Model\ThumbnailGenerator\DocumentThumbnailGenerator:
        resolution: 120
        supportedExtensions:
          - pdf
          - eps
          - ai
        paginableDocuments:
          - pdf
        # if set, the DocumentThumbnailGenerator will be used when possible, even if the
        # used Imagine driver would usually prohibit it's use (because GD doesn't do PDF)
        overrideImagineDriverCheck: false
      Neos\Media\Domain\Model\ThumbnailGenerator\FontDocumentThumbnailGenerator:
        supportedExtensions:
          - ttf
          - otf

  DocTools:
    collections:
      Media:
        commandReferences:
          'Media:Commands': true
        references:
          'Media:ViewHelpers': true
          'Media:Validators': true
    commandReferences:
      'Media:Commands':
        title: 'Media Command Reference'
        packageKeys:
          'Neos.Media': true
        savePathAndFilename: '%FLOW_PATH_PACKAGES%Neos/Neos.Media/Documentation/References/Commands.rst'
    references:
      'Media:Validators':
        title: 'Media Validator Reference'
        savePathAndFilename: '%FLOW_PATH_PACKAGES%Neos/Neos.Media/Documentation/References/Validators.rst'
        affectedClasses:
          parentClassName: Neos\Flow\Validation\Validator\AbstractValidator
          classNamePattern: '/^Neos\\Media\\Validator\\.*$/i'
        parser:
          implementationClassName: Neos\DocTools\Domain\Service\FlowValidatorClassParser
      'Media:ViewHelpers':
        title: 'Media ViewHelper Reference'
        savePathAndFilename: '%FLOW_PATH_PACKAGES%Neos/Neos.Media/Documentation/References/ViewHelpers.rst'
        affectedClasses:
          parentClassName: Neos\FluidAdaptor\Core\ViewHelper\AbstractViewHelper
          classNamePattern: '/^Neos\\Media\\ViewHelpers\\.*$/i'
        parser:
          implementationClassName: Neos\DocTools\Domain\Service\FluidViewHelperClassParser
          options:
            namespaces:
              neos.media: Neos\Media\ViewHelpers

  Fusion:
    defaultContext:
      Neos.Media.Assets: 'Neos\Media\Eel\AssetsHelper'
